### PR TITLE
Everything to same folder. More .env variables added.

### PR DESCRIPTION
**Pull request by LodeKennes**

### CODE REVIEW

**Comment by LodeKennes** [comment]
Everything is now the the same folder. Changed to v1.1.7 again because v1.3.0 show bugs. Let me know what you think.

**Comment by SebastianStehle** [comment]
Nice

* Can we move to 1.3.1? Have not heard any complaints yet
* The github setting is obsolete
* Can you also move the settings for external auth providers to the .env file?

We can also merge first, just some comments.

**Comment by LodeKennes** [comment]
Ah, I see 1.3.1 has only been published a few minutes ago. Which Github setting do you mean?

IDENTITY__GITHUBCLIENT and IDENTITY__GITHUBSECRET ?

Will move those changes.

**Comment by SebastianStehle** [comment]
Both are obsolete

**Comment by LodeKennes** [comment]
It's done. Should be ready for merge.

**Comment by SebastianStehle** [comment]
Awesome :)

**Pull request merged**
